version: '3'
services:
  app:
    container_name: mongoyoutube
    restart: always
    build: .
    ports:
      - '4000:3000'
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo:27017
      DB_NAME: addressbook
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-1
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo: {}



